@startuml


frame 用户信息 {
object user_info {
    user_id
    name
    email
    password
    sex
    phone
    source
    country_id
}



object user_extra {
    user_id
    is_mail_subscribe
    os_open_push
}
}

frame 用户反馈{
object user_feedback {
    id
    user_id
    content
}
}

frame 收件地址{
object user_address {
    id
    user_id
    city_id
    phone
    address
}
}

frame 订单 {
	object order_info {
		id
		user_id
		pay_status
		ship_status
		price_info
		marketing_info
		payment_info
		pay_code
	}

	object order_goods {
		id
		order_id
		user_id
		goods_id
	}
}

frame 商品{
object goods_info {
    goods_id
    goods_sn
    goods_info
    goods_image
    remain_count
    status
}
}

frame 商品收藏{
object goods_favorite {
    id
    user_id
    goods_id
}
}


frame 类目 {
object category {
    id
    parent_id
    child_id
    category_info
}

object channel {
    id
    code
    meta_info
}
}

frame 地址库{
object country {
    id
    country_code
    country_name
    national_flag
    status
}

user_info .. country: 1:1

object province {
    id
    code
    name
}

object city {
    id
    name
    code
}
}


frame 购物车{
object shopping_cart {
    id
    user_id
    goods_id
    goods_num
}
}

frame 评论 {
    object comment {
        comment_id
        user_id
        goods_id
        content
        status
    }
}


user_info .. user_address : 1:N
user_info .. user_extra: 1:1
country .. province : 1:N
province .. city : 1:N
user_address .. city : 1:1

user_info .. comment : 1:N
goods_info .. comment : 1:1

user_info .. goods_favorite : 1:N
goods_info .. goods_favorite : 1:1

user_info .. shopping_cart : 1:N
shopping_cart .. goods_info : 1:1

user_info .. user_feedback : 1:N

channel .. category : 1:N
category .. category

user_info .. order_info : 1:N
order_info .. order_goods : 1:N
order_goods .. goods_info : 1:1

@enduml
