@startuml

object user_info {
    user_id
    name
    email
    password
}

object user_address {
    id
    user_id
    city_id
    phone
    address
}

object order_info {
    id
}

object goods_info {
    id
    goods_sn
    goods_description
    goods_image
    status
}

object goods_favorite {
    id
    user_id
    goods_id
}

object category {
    id
}

object channel {
    id
}

object country {
    id
    code
    name
}

object province {
    id
    code
    name
}

object city {
    id
    name
    code
}

object cart {
    id
}

object exchange {
    id
}

user_info .. user_address : 1:N
country .. province : 1:N
province .. city : 1:N
channel .. category : 1:N

user_info .. order_info
order_info .. goods_info

@enduml